// AUTO-GENERATED and validated by AlgoReel's codegen path
// (algoreel-mcp/src/algorithms/sandbox.ts) on 2026-08-24T16:04:11.391Z.
// Implementation of dfs, generated by the algorithm agent.
//
// Validated once via sandboxed execution against a real bfs/dfs
// reference (see sandbox.ts's referenceBFSOrder/referenceDFSOrder)
// before being cached here. From this point on it's a real, permanent
// algorithm file, run in-process like any hand-written one — no further
// sandboxing on load.
import { createTracedGraph } from "../graphTrace";
import type { AlgorithmResult } from "../types";
import type { TracedGraph } from "../graphTrace";

export const DESCRIPTION = "Implementation of dfs, generated by the algorithm agent.";

export interface GeneratedGraphInput {
  nodes: string[];
  edges: [string, string][];
  start: string;
}

function run(trace: TracedGraph): void {
  const dfsHelper = (node: string): void => {
    if (trace.isVisited(node)) return;
    trace.visit(node);
    for (const neighbor of trace.neighbors(node)) {
      trace.traverseEdge(node, neighbor);
      dfsHelper(neighbor);
    }
  };

  dfsHelper(trace.start);
}

export function dfs({ nodes, edges, start }: GeneratedGraphInput): AlgorithmResult {
  const { trace, operations } = createTracedGraph(nodes, edges, start);
  run(trace);
  return { operations, summary: "Ran the generated \"dfs\" implementation from \"" + start + "\"." };
}
